image: node:7

stages:
  - test

before_script:
  - rm -rf anno-common
  - git submodule sync --recursive
  - git submodule update --init --recursive

test:
  stage: test
  script:
    - npm install
    - npm test
  # cache:
  #   paths:
  #   - node_modules/
